### ISSUE TITLE
[Feliz.Lit] Static templates in lit-html 2.0

### ISSUE THREAD

**Issue by alfonsogarciacaro** [alfonsogarciacaro/Fable.Lit#4]
I tried the Fable.Lit and at the beginning they seemed to be working but then I realized the whole DOM was updated for every render. Some debugging revealed the reason is in lit-html 2.0 (currently rc-004) they're using [a WeakMap to identify templates already rendered](https://github.com/lit/lit/blob/761375ac9ef28dd0ba8a1f9363aaf5f0df725205/packages/lit-html/src/lit-html.ts#L1164-L1165). I think I've managed to fix this in Fable by compiling to JS template strings (even if I've to wrap them again to conform to `FormattableString` API), but with `Feliz.Lit.toLit` this is not possible because templates are generated on-the-fly.

A workaround is tricky. Even if we could keep a "static" reference (but that can be garbage collected) per `toLit` call and have our own WeakMap, we cannot be sure the template will be the same every time because Feliz code is dynamic. The only solutions I can think of atm are:
- use a lit-html directive to render to mount directly on the DOM, but then we don't have the diffing unless we import a virtual dom like Snabbdom or a similar technique
- focus on interaction with React so we can use "real" Feliz
- try to "pre-compile" Feliz.Lit templates somehow
- just forget about converting Feliz.Lit code to Lit (except maybe for the styles).

What do you think @AngelMunoz?

**Comment by AngelMunoz** [comment]
this might sound silly (and let me know if it is) and I might not be understanding Lit's code there but if we produce a string without holes would that allow Lit's caching to prevent re-rendering all of the time until said string changed?

I would think that if in the end we produce a different string it would create a different cache entry and so on

also what about getting a hash of the whole node and using it as the only whole on that template? 

the hash would need to be reproducible, I'm not sure if that can be done with Feliz.Lit

otherwise I don't think there might be an easy solution here ('ill try to think on something else) anyways  if that's not the case, we can always point to Sutil if the users want a type safe DSL that uses DOM nodes under the hood (making it as compatible as Lit with the rest of the ecosystem)

**Comment by alfonsogarciacaro** [comment]
If I understand the code of lit-html 2.0 correctly, instead of building the TemplateResult directly in the `html` function they pass the deconstructed template more or less as is (the strings parts and the holes) with some metadata, then parse the template in `render` and cache the result in a `WeakMap` cache. It's important to note they use the `strings` array as the keys of the cache for two reasons: first it's ok the holes change, and second `WeakMap` keys must be objects (not strings or numbers).

Sorry I forgot to include it in the solutions above, but a possibility is to use our own cache for example with a hash as you said. The problem is we cannot use a `WeakMap` because we don't have a static object reference. So the cache would grow indefinitely as the app runs. Probably it wouldn't be an issue in real apps with not many Feliz templates embedded in Lit, and we could clean it up from time to time, but still it's not a nice design.

**Comment by AngelMunoz** [comment]
> but still it's not a nice design

I agree

> Probably it wouldn't be an issue in real apps with not many Feliz templates embedded in Lit

Hmm that could be a problem then from feedback I've got over the last few days there are people who want to run pure Feliz.Lit

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm more and more convinced that we shouldn't put too much effort on haunted virtual components. The library author [doesn't seem to use them](https://github.com/matthewp/haunted/issues/69#issuecomment-468479562) so that's a sign they won't see a lot of love in the near future. Probably we can remove the `VirtualComponent` from Fable.Haunted (sorry!) and just recommend the library for users who want to declare web components in a React fashion. At one point we should also make it possible to declare web components à-la-Lit (or even the standard way).

If users want to keep some local state between lit-html renders (without declaring an actual web component), this [simple hook implementation](https://github.com/alfonsogarciacaro/Fable.Lit/blob/master/src/Lit/Hook.fs) seems [to work](https://github.com/alfonsogarciacaro/Fable.Lit/blob/566d200378042e65efdeb68f5f038862dbd07d57/sample/src/App.fs#L104-L122) and doesn't require extra dependencies so hopefully that's enough for now.

I've written many adapters for cool JS libraries (Vue, Svelte) but none has wide adoption. I believe the reason is that most users have already written big apps with React and it's too painful to rewrite them. Even for new projects it's difficult to use a new library if you've already many components (and workflows) written in React. I think being able to write HTML in F# is hugely beneficial for Fable apps but we need to focus on integration and minimize the steps for that 👍 

I've published the packages with the new names. Note the package ids are prefixed with `Fable.` but the projects are Lit/Lit.React/Lit.Elmish/Lit.Feliz.

**Comment by AngelMunoz** [comment]
> Hmm, I'm more and more convinced that we shouldn't put too much effort on haunted virtual components

I agree, all of the scheduler stuff seems un-intuitive at best and I think providing better integration with Lit could prove to be a better option

> At one point we should also make it possible to declare web components à-la-Lit (or even the standard way).

I could re-invest time on the function based web components I was thinking in Sutil but adding a couple of inspirations from haunted

what do you think about actually allowing class style components here? I know classes are sometimes... too much for some people 
and other kind of annoying topic are decorators but there are javascript API's and with the tagged templates classes are more JSX/TSX stylish I'll explore this area but I don't think I'll spend an extra amount of time for that

> I've written many adapters for cool JS libraries (Vue, Svelte) but none has wide adoption. I believe the reason is that most users have already written big apps with React and it's too painful to rewrite them. 

I wouldn't expect react users to move, but Ideally I'd expect new users or users familiars with other common frameworks to pick up the familiar html syntax and then move on to more F# flavored stuff either with Feliz.Lit or the original Feliz


> I think being able to write HTML in F# is hugely beneficial for Fable apps but we need to focus on integration and minimize the steps for that 👍

I think I'll spend some time here to put out resources regarding these, either docs or samples and blog entries if the information is there hopefully it will be easier for new users to pick up

> I've published the packages with the new names. Note the package ids are prefixed with Fable. but the projects are Lit/Lit.React/Lit.Elmish/Lit.Feliz.

I'll update the haunted bindings to use lit2 (remove the virtual components, /sadpanda) and the dotnet templates as well 

Thank you very much for your time on this! 
I really appreciate it I'll try to make it worth it 😆 with more content targeted to userland

**Comment by AngelMunoz** [comment]
I updated all of the samples and templates plus a blog post :) at least what I have been sampling hasn't broken with lit-html v2

also btw I did some cursed experiments here to see how dificult class style components with lit can be (i.e the _the standard way_) because some people (outside F#) really seem to like the JSX style but I don't think I'll pursue that goal too much I think at least for now the standard way for F# (data and functions) is good enough

in case you want to check those as well here they are

https://github.com/AngelMunoz/cursed-lit-experiments/blob/73fa896b9362cc91c103e1edb5ef560241c5372f/src/Main.fs#L92-L113

**Comment by alfonsogarciacaro** [comment]
In principle it shouldn't be an issue to use classes for web components. Although I'm checking Lit components and they seem to be very Typescript-oriented so not sure whether they will be a good fit for F#, moreover as Lit's website recommends mixins and controllers to organize (which reminds me a bit of the problems we had with React classes and Higher-order-components). We also need to take into account the _upgrade path_: that's how many

Fable 3.3 will include decorators, not exactly the same as in Typescript but will work in a similar fashion. We could use to define web components out of a function

**Comment by AngelMunoz** [comment]
The javascript docs are quite late but they are comming, AFAIK Lit will support javascript only components as well, the decorators get translated into static properties I had some success on that repository I think If you don't mind we could release class based bindings as part of an extensions package, I don't think people will opt in for that too much

Haunted actually uses the same approach I had in mind with https://github.com/davedawkins/Sutil/issues/32 albeit in a more formalized fashion, I think if we wanted to go that route we could simply provide our own factory function that does that I'll see if I can get something later on but I feel we're very much on route to have most things supported in this package

**Comment by AngelMunoz** [comment]
Regarding function based components with Lit@2 check this https://github.com/alfonsogarciacaro/Fable.Lit/pull/7#issuecomment-909549075

**Comment by AngelMunoz** [comment]
>The javascript docs are quite late but they are comming

The Lit JS documentation samples is in preview you can access it with the following link https://lit.dev/docs/?mods=jsSamples

**Comment by alfonsogarciacaro** [comment]
Let's keep the Lit.Feliz project in the repo just in case, but we can "deprecate" it by removing it from the sample and the readme. We can revisit this if we still feel the need of using Lit with a typed API.

**Comment by AngelMunoz** [comment]
sounds good, I will update the dotnet templates as well
