### ISSUE TITLE
[Feliz.Lit] Set Properties

### ISSUE THREAD

**Issue by AngelMunoz** [alfonsogarciacaro/Fable.Lit#5]
(this may be better in Feliz.Engine, feel free to move it there if necessary)

Currently with the Feliz flavor you can only set attributes via `Attr.custom("my-attribute", "it's value")` but unless I'm lost (very likely) there are not ways to set properties of an element with the template strings flavor you can do 
```fsharp
let myValue = "some value"
let myObj = {| value = 10 |}
```

```html
<some-element my-attribute={myValue} .myProperty={myObj}></some-element>
```

it would be ideal to have this on the Feliz flavor as well

**Comment by alfonsogarciacaro** [comment]
It's probably better to fix it here, as Feliz.Engine just deals with "raw" html. I've added `Lit.Feliz.prop` so you can do:

```fsharp
Feliz.prop "myProperty" {| value = 10 |}
```

which in JS/lit-html will become something like:

```js
html`<some-element .myProperty=${ ({ value: 10 }) }></some-element>`
```
