### ISSUE TITLE
[Lit]: error FABLE: Unexpected base call expression, please report

### ISSUE THREAD

**Issue by AngelMunoz** [alfonsogarciacaro/Fable.Lit#6]
When compiling on a fresh project the first time I'm getting this error
```
C:/x/Fable.Haunted/src/Fable.Haunted.Store/.fable/Fable.Lit.1.0.0-beta-002/Hook.fs(1,1): error FABLE: Unexpected base call expression, please report
Compilation failed
```
the error goes away when you try to compile again

**Comment by alfonsogarciacaro** [comment]
Are you using Fable 3.3.0-beta-002. This is needed to run the latest packages.

**Comment by kierepka** [comment]
> Are you using Fable 3.3.0-beta-002. This is needed to run the latest packages.

Problem is in .config folder where fable version should be:
```
"tools": {
    "fable": {
      "version": **"3.3.0-beta-002"**,
      "commands": [
        "fable"
      ]
```

**Comment by AngelMunoz** [comment]
Ah yes I included the package but I was using an older versionon the config, thanks!
